{% set version = "0.32.1" %}

package:
  name: uvicorn-split
  version: {{ version }}

source:
  url: https://github.com/encode/uvicorn/archive/refs/tags/{{ version }}.tar.gz
  sha256: fc494193b6cf58db1d732e93e1342ac069b6f7be7d01ad6a3c86b14a9fc3d28a

build:
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
outputs:
  - name: uvicorn
    script: uvicorn_build.bat  # [win]
    script: uvicorn_build.sh  # [not win]
    build:
      skip: true  # [py<38]
      entry_points:
        - uvicorn = uvicorn.main:main
    requirements:
      host:
        - python
        - pip
        - hatchling
      run:
        - python
        - click >=7.0
        - h11 >=0.8
        - typing_extensions >=4.0  # [py<311]
    test:
      imports:
        - uvicorn
      requires:
        - pip
      commands:
        - pip check
        - uvicorn --help

  - name: uvicorn-standard
    build:
      # s390x missing watchfiles
      skip: true  # [py<38 or s390x]
    requirements:
      host:
        - python
        - pip
        - {{ pin_subpackage('uvicorn', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('uvicorn', exact=True) }}
        - colorama >=0.4  # [win]
        - httptools >=0.6.3
        - python-dotenv >=0.13
        - PyYAML >=5.1
        - uvloop >=0.14.0,!=0.15.0,!=0.15.1  # [not win]
        - watchfiles >=0.13
        - websockets >=10.4
    test:
      source_files:
        - pyproject.toml
        - tests
      requires:
        - pip
        - pytest
        - pytest-mock
        - httpx
        - wsproto
        - trustme

      {% set pytest_ignore = '--ignore="tests/middleware/test_wsgi.py"' %}
      {% set pytest_ignore = pytest_ignore + ' --ignore="tests/supervisors/test_signal.py"' %}
      {% set pytest_ignore = pytest_ignore + ' --ignore="tests/test_server.py"' %}

      {% set pytest_skip = "socket_bind" %}
      {% set pytest_skip = pytest_skip + " or config_log_effective_level" %}
      {% set pytest_skip = pytest_skip + " or test_run" %}

      commands:
        - pip check
        - pytest -v {{ pytest_ignore }} -k "not ({{ pytest_skip }})"  # [not (osx and x86)]
        - pytest -v {{ pytest_ignore }} -k "not ({{ pytest_skip }})" -m "not reloader_class"  # [osx and x86]

      imports:
        - uvicorn.supervisors.watchfilesreload

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server.
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  feedstock-name: uvicorn
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
