{% set name = "uvicorn" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0515f2628029fa1bb9167cec2e2003ddaed8dee369c400f2f509e27ac08fe1e4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"
  skip: True  # [py2k]
  entry_points:
    - uvicorn = uvicorn.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - h11
    - websockets >=6.0
    - uvloop  # [not win]
    - httptools  # [not win]
    - wsproto =0.13

test:
  imports:
    - uvicorn
  commands:
    - uvicorn --help

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'The lightning-fast ASGI server. 🦄'
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
