{% set version = "0.16.0" %}

package:
  name: uvicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: eacb66afa65e0648fcbce5e746b135d09722231ffffc61883d4fac2b62fbea8d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - uvicorn = uvicorn.main:main
  skip: true # [py<=37 or s390x]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - asgiref >=3.4.0
    - click >=7.*
    - h11 >=0.8
    - typing-extensions  # [py<38]

test:
  requires:
    - pip
  imports:
    - uvicorn
  commands:
    - pip check
    - uvicorn --help

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server. 🦄
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
