{% set version = "0.13.0" %}

package:
  name: uvicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: 28420526640d800aabe648038f8e2ea8ba2a8bdc363002eecd5dfc57a0f75ab7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - uvicorn = uvicorn.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click 7.*
    - h11 >=0.8
    - typing_extensions  # [py<38]
    - websockets 8.*
    - httptools 0.1.*  # [not win]
    - uvloop >=0.14  # [not win]
    - watchgod 0.6.*
    - python-dotenv >=0.13
    - pyyaml >=5.1

test:
  requires:
    - pip
  imports:
    - uvicorn
  commands:
    - pip check
    - uvicorn --help

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server. 🦄
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
