{% set version = "0.20.0" %}

package:
  name: uvicorn-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: a4e12017b940247f836bc90b72e725d7dfd0c8ed1c51eb365f5ba30d9f5127d8

build:
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling
    - setuptools
    - wheel

outputs:
  - name: uvicorn
    script: uvicorn_build.bat  # [win]
    script: uvicorn_build.sh  # [not win]
    build:
      skip: true  # [py<38]
      entry_points:
        - uvicorn = uvicorn.main:main
    requirements:
      host:
        - python
        - pip
        - hatchling
        - setuptools
        - wheel
      run:
        - python
        - click >=7.*
        - h11 >=0.8
    test:
      imports:
        - uvicorn
      requires:
        - pip
      commands:
        - pip check
        - uvicorn --help

  - name: uvicorn-standard
    build:
      skip: true  # [py<38]
      # watchfiles is missing on s390x and win-64
      skip: true  # [s390x or win]
    requirements:
      host:
        - python
        - pip
        - {{ pin_subpackage('uvicorn', exact=True) }}
      run:
        - {{ pin_subpackage('uvicorn', exact=True) }}
        - colorama >=0.4  # [win]
        - httptools >=0.5.0
        - python-dotenv >=0.13
        - PyYAML >=5.1
        - uvloop >=0.14.0,!=0.15.0,!=0.15.1  # [not win]
        # TODO: add watchfiles for win-64.
        # 2023/03/02: There were CI issues with building watchfiles on Windows related to python executables. 
        - watchfiles >=0.13  # [not win]
        - websockets >=10.4
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - uvicorn.supervisors.watchfilesreload

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server.
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  feedstock-name: uvicorn
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
