appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WQeSQyAqjSyxdQ7f813mqd/Tdgrr+8U3jomvYZzDgtfiLkTRqBpTpxB3BhucQzUPR1AjddL5F/pqhjnRoqU9aJhvhviStEbNJMTlBi8h4Gn6MEOKylPP0NgoMBoLT1B5JWNKyDyyv5jJgHaa5iodFRl2Iy0z80fEl6dbQ9ELyv9PcX7KC2kB23sMdS+s1Rhw95OWOcEffMdBlcEjMlWjTONQPymLmt3n7reQxxFL3IbNVH86DNlYwecSFCsAgZO+9LwQlAJxfjgHEqXo67ckU41dJ3lIbuk13/jOkV9XvUKQxqt8LmXHnJ3lIbPIKssIvV+qSiEN4w+aDq71xuYQ/jVRddPHzSX+lnAj7h0VjxqKme8IMDj9AyDfsywOjxEiSY6FACgmu4YwNXouP/PJktYntSPwyBVqX58rVsPDbt0keh7Mhhhh4tEvNHVxIrrR+cSvlO7EggbCuw9FohT7nJMKJ1W/o9//wckhIJCZTXwrdwg19e835gBB5a0p597SZORpwWHlhEFcMQfT/drK8kHDcWFZUE7iMs8j6jBuPVVqlIoZijEthnIQeff5fXN9b4nie4W7lb3tAhQQc8lPro7hNxWZJer1Mkad8LKksRVPJc6fhqMnOUiCrzNKx3JyluYQYaSy+2WMPtuRoAeyMbbjyzapDinyWd3InZh9bUI=}
provider:
  win: azure
