travis:
  secure:
    BINSTAR_TOKEN: WYuw2snHyQ/r/YLwtNPLZMvTq4yhGdZWThVInWQu8eFSAdKcZwYPkEAHYYRrwEaA5JFDWHlTHQzOT4DfLQtwZ+C098TlXpj/Y0DkOAK4OHfM7sY2O0n9rzLI/Px50iWEs+2rEsnCG6LG9J15BJsu+N4SvZ5X0Sbv/V5eGy2coeTeXiSe0R/sOOk8oebBcEUH60pHNJ5ss6isGHsxNzBBMrLTm2ZwZT6hgBUuKvA9hz1Ltyj6D7SocNH9w1BwAh5TzoRkAcF+z0rCB5+nT0PQRwtSY2udGn/aTdumTl1Wwmp9SvZDsd5WZ6bdevHuoRrftnUGd7D82RrMvJfgCpT87vE8Mg0xSjmfJwSUDfm96gxEGo0j7SmHpfCQSfoXjPQDF/Z1FQGAcqGNlpp8RyrjmQzIEjOomuPNicVuPbKjsA9xjMDiLxqnn8VHCGhG29w3MW1jww1KtbkpINq2jIDgo/VX7UgK58UA44HkogEmPhC8c2gGRitvFWp33aC6hky4tXUlsAXjLt7e84Hy3u+vWUD8Eq4vAm86zA/o6qd4IzvFOFS5xpGot5iHVeUxsruy8W6Wzyoj1QeGmaMq5Ufak0UYu35XlUPlHvrbvHgxBlbBI11fdefHbDcSnBRJVTsoH7K+qD/5p6ad4t+bhvzb47FyzpZs+x8U+TVzWYklijU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
